[package]
name = "y2021d19"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y2021d19"
path = "src/19.rs"

[dependencies]
aoclib = "0.2.1"
itertools = "0.14.0"
regex = "1.12.2"
thiserror = "2.0.17"
